config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'#, as: 'helf'  # as:でスペル変更
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Ruby on Rails by Rich
  </small>
  <%= render 'layouts/nav' %>
</footer>

app/views/layouts/_head.html.erb
<head>
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "my app", root_path, id: "logo" %>
    <%= render 'layouts/nav' %>
  </div>
</header>

app/views/layouts/_nav.html.erb
<nav>
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "ホーム", root_path %></li>
  <li><%= link_to "ヘルプ", help_path %></li>
    <% if logged_in? %>
      <li><%= link_to "マイページ", current_user %></li>
      <li><%= link_to "ユーザー一覧", users_path %></li>
      <li><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
      <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "ログイン", login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do | message_type, message | %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>